databaseURI: 'mongodb://localhost:27017/dev'
appId: 'myAppId'
masterKey: 'myMasterKey'
fileKey: 'optionalFileKey'
serverURL: 'http://localhost:8080/parse'
verbose: true
push:
  android:
    senderId: '' # The Sender ID of GCM
    apiKey: '' # The Server API Key of GCM
  ios: 
    pfx: '' # The filename of private key and certificate in PFX or PKCS12 format from disk  
    cert: '' # If not using the .p12 format, the path to the certificate PEM to load from disk
    key: '' # If not using the .p12 format, the path to the private key PEM to load from disk
    bundleId: '' # The bundle identifier associate with your app
    production: false # Specifies which environment to connect to: Production (if true) or Sandbox